### ISSUE TITLE
Fix issues

### ISSUE THREAD

**Issue by denisflorkin** [uxilab/uxi-business#3]
- naming:
  - [x] userMessageProviders.js export names export UserFeedbackProvider
  - [x] MessageTitle.js expotrs a named export AlertTitle
  

- useless export
  - [x] #5 GlobalMessage.js is exprting nothing
  

- confusion
  - [x] it is not clear from the name of the action or signature what they do
    - clearing a single action ? 
    - clearing all action of given context
- [x] #4 since the action identifier are identical to the widget ones, and we have a redu er in uxi-b and in widget "reacting" to those event, this creates a double notification situation.

- bugs:
  - [x]  #6 clearing notification by licking close icon is not working, but the timeout is, ti is because the wrong args are passed/expected by the handler
